add InputSourceSwitch
Hammerspoon/Spoons pull request #243
Opened 2021-07-26 06:09 UTC by eks5115

Automatically switch the input source when switching applications.

2021-12-16 22:58 UTC, cmsj commented
Apologies for not getting to this sooner...

I don't think we should host a Spoon here that includes an embedded binary. I'm also curious what that binary does that Hammerspoon's API can't already do?

2021-12-16 22:59 UTC, cmsj requested changes
Note: Can't merge this while there is an included binary executable.

2022-02-15 07:59 UTC, eks5115 commented
> Note: Can't merge this while there is an included binary executable.

@cmsj After I read the API of hs.keycodes, I deleted bin. Thank you！

2024-08-07 12:59 UTC, cmsj approved these changes

2024-08-07 13:00 UTC, merged